version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001